version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    restart: always
    ports:
      - 27017:27017
    networks:
      - wallet_network

  redis:
    image: redis:latest
    container_name: "redis"
    restart: always
    ports:
      - 6379:6379
    networks:
      - wallet_network


  auth-service:
    build: ./auth
    container_name: "auth-service"
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb
      - redis
    networks:
      - wallet_network

  wallet-service:
    build: ./walletService
    container_name: "wallet-service"
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongodb
      - redis
      - auth-service
    networks:
      - wallet_network

  transaction-service:
    build: ./transaction
    container_name: "transaction-service"
    restart: always
    ports:
      - 8082:8082
    depends_on:
      - mongodb
      - wallet-service
    networks:
      - wallet_network

  fastapi-service:
    build: ./fastapi-service
    container_name: "fastapi-service"
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    networks:
      - wallet_network

networks:
  wallet_network:
    driver: bridge
