version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - wallet-network

  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - wallet-network


  auth-service:
    build: ./auth
    container_name: auth-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/digital-wallet-system
    networks:
      - wallet-network

  wallet-service:
    build: ./walletService
    container_name: wallet-service
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
      - redis
      - auth-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/digital-wallet-system
    networks:
      - wallet-network

  transaction-service:
    build: ./transaction
    container_name: transaction-service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
      - kafka
      - wallet-service
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/digital-wallet-system
    networks:
      - wallet-network

  fastapi-service:
    build: ./fastapi-service
    container_name: fastapi-service
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - wallet-network

volumes:
  mongo_data:

networks:
  wallet-network:
    driver: bridge
